### PR TITLE
Sort the activities alphabetically

### PR DESCRIPTION
**Pull request by alapitz**
Added an alphabetical sort to the activities resulting in the input fields being sorted.

### CODE REVIEW

**Comment by nicoduj** [comment]
thnak you, will merge this asap and release a version after some tests.

**Comment by alapitz** [comment]
Perfect, Thanks!

**Comment by nicoduj** [comment]
Merged and  released, thank you. I just made some modification : a new option to set the order, which remains by default as it was. Alpha sort ad activity roder in harmony conf can be used (even if the activityorder in the conf is not the same as in the app from what I see by my side).

thank you, and have a nice end of year !

**Comment by alapitz** [comment]
Thanks for adding this, Have a great new year!

**Comment by maisun** [comment]
Hi, nice feature, thanks! However I tried on my existing setup and it doesn't seem to work. Should I remove the accessory and re-add it back?

**Comment by alapitz** [comment]
Oh interesting. I did remove and re-add the accessory while testing it
myself but that shouldn't be required. Do you get any errors?

**Comment by nicoduj** [comment]
Hi, I did not integrate the last PR right now, I am a bit concerned about the fact to put the order as an id, I want to test more before validating it. However, I also wanted to test by removing the accessory, because I think home app has itself some cache and with same id does not recreate the inputs . Let me know, will try to take more time to look into it.

**Comment by alapitz** [comment]
No worries, I'm happy to do validation as well. It is quite a bit
bigger change from the last one. The ID for input sets the order in which
it appears, so the way it works before the PR is pseudo random based on the
ids Harmony assigns the activities which could be alphanumeric or happen to
be the order which you set them in the app.

**Comment by maisun** [comment]
Hi, I'm not a bit confused. Is the change ready for test in version 1.5.4?
What I want to achieve is to follow the order as specified in "activitiesToPublishAsInputForTVMode" as config below:
           "SortInput": 2,
            "mainActivity": "IP Radio",
            "activitiesToPublishAsInputForTVMode": [
                "IP Radio",
                "FM Radio",
                "Music",
                "Movie",
                "Game"
            ]

Will the configuration work or do I misunderstand something?

**Comment by alapitz** [comment]
Hm.. I suspected this might be the difference between our setups. I don't
have any activities to publish set on my config and just all the activities
that come from harmony by default.  I'll add some custom activities and see
if I can catch an error

My current config:
        {
            "name": "Harmony - Master Bedroom",
            "hubIP": "172.16.72.255",
            "hubName": "Master Bedroom",
            "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,
            "HUB_CONNECT_TIMEOUT": 10000,
            "HUB_SEND_TIMEOUT": 30000,
            "publishAllTVAsExternalAccessory": true,
            "TVAccessory": true,
            "SortInput": 2,
            "mainActivity": "Watch Apple TV",
            "switchAccessories": false,
            "otherPlatforms": [
                {
                    "name": "Harmony - Family Room",
                    "hubIP": "172.16.188.11",
                    "hubName": "Family Room",
                    "TVAccessory": true,
                    "SortInput": 2,
                    "mainActivity": "Watch Apple TV"
                }
            ],
            "platform": "HarmonyHubWebSocket"
        }

**Comment by alapitz** [comment]
Hm.. adding activitiesToPublishAsInputForTVMode worked fine for me. What
happens for you? Are you seeing any errors in the log?

Thanks for the help on this! I love your plugin.
-Adam

**Comment by maisun** [comment]
> Hm.. adding activitiesToPublishAsInputForTVMode worked fine for me. What happens for you? Are you seeing any errors in the log? Thanks for the help on this! I love your plugin. -Adam On Sun, Jan 2, 2022 at 10:47 AM Adam LaPitz ***@***.***> wrote:
> […](#)

I'm now trying to remove the plugin, clean the cache and add it back. Will report back how it goes.

**Comment by maisun** [comment]
Hi, would like to report back after I have removed the plugin, cleared cache (manually delete anything related to Harmony in HomeBridge folder), re-install and re-add the TV accessory, unfortunately the order is still not working for me. I tried both with and without "activitiesToPublishAsInputForTVMode", same result. Also tried with "SortInput": 1 doesn't work for me either.
Tested with plugin version 1.5.4 and HomeBridge version 1.3.9.

**Comment by alapitz** [comment]
Thanks for checking. What iOS or Mac OS are you trying on?

Just to double check you don’t get any errors in the log?
________________________________

**Comment by maisun** [comment]
> Thanks for checking. What iOS or Mac OS are you trying on? Just to double check you don’t get any errors in the log?
> […](#)

I use iOS 15.2 on my iPhone. Same result with my Mac on 12.1. No errors but HomeBridge print out Hugh amount of logs, is there anything I should search for (for example any indication if the config even kicks in)?

**Comment by alapitz** [comment]
If it is working correctly you should see the "Creating Input" change based
on the sort order you've got set in the config.

For example:

[02/01/2022, 10:55:34] Homebridge v1.3.9 (HAP v0.9.8) (Homebridge D88C) is
running on port 51884.
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Master
Bedroom)INFO - Adding Accessory : Harmony - Master Bedroom-TV
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Master
Bedroom)INFO - configuring Main TV Service
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Master
Bedroom)INFO - Creating TV Service
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Master
Bedroom)INFO - Configuring Main Activity Watch Apple TV
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Master
Bedroom)INFO - Creating TV Speaker Service
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Master
Bedroom)INFO - Creating Input Service - Watch Apple TV
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Master
Bedroom)INFO - Creating Input Service - Watch TV
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Master
Bedroom)INFO - setupFoundAccessories - TV accessory added as external
accessory
[02/01/2022, 10:55:36] Harmony - Master Bedroom-TV 0B48 is running on port
38137.1
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Family
Room)INFO - Adding Accessory : Harmony - Family Room-TV
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Family
Room)INFO - configuring Main TV Service
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Family
Room)INFO - Creating TV Service
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Family
Room)INFO - Configuring Main Activity Watch Apple TV
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Family
Room)INFO - Creating TV Speaker Service
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Family
Room)INFO - Creating Input Service - Watch Apple TV
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Family
Room)INFO - Creating Input Service - Play Xbox
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Family
Room)INFO - Creating Input Service - Portal
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Family
Room)INFO - Creating Input Service - Play Switch
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Family
Room)INFO - Creating Input Service - Play SNES
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Family
Room)INFO - Creating Input Service - Play NES
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Family
Room)INFO - Creating Input Service - Listen To Sonos
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Family
Room)INFO - Creating Input Service - Laptop
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Family
Room)INFO - Creating Input Service - Watch TV
[02/01/2022, 10:55:36] [Harmony - Master Bedroom] (Harmony - Family
Room)INFO - setupFoundAccessories - TV accessory added as external accessory
[02/01/2022, 10:55:36] Harmony - Family Room-TV 2D56 is running on port
45799.

**Comment by maisun** [comment]
> If it is working correctly you should see the "Creating Input" change based on the sort order you've got set in the config. 
> […](#)

Thanks, mine is below:
.[37m[1/2/2022, 8:56:06 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Adding Accessory : Living Room Media Center-TV
.[37m[1/2/2022, 8:56:06 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - configuring Main TV Service
.[37m[1/2/2022, 8:56:06 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Creating TV Service
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Creating Input Service - FM Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping Mute for FM Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping VolumeDown for FM Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping VolumeUp for FM Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping DirectionDown for FM Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping DirectionLeft for FM Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping DirectionRight for FM Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping DirectionUp for FM Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping Select for FM Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping Return for FM Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Creating Input Service - Game
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping Mute for Game
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping VolumeDown for Game
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping VolumeUp for Game
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping DirectionDown for Game
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping DirectionLeft for Game
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping DirectionRight for Game
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping DirectionUp for Game
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping Select for Game
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping Return for Game
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Configuring Main Activity IP Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Creating TV Speaker Service
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Creating Input Service - IP Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping Mute for IP Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping VolumeDown for IP Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping VolumeUp for IP Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping DirectionDown for IP Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping DirectionLeft for IP Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping DirectionRight for IP Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping DirectionUp for IP Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping Select for IP Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping Return for IP Radio
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Creating Input Service - Music
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping Mute for Music
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping VolumeDown for Music
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping VolumeUp for Music
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping DirectionLeft for Music
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Creating Input Service - Movie
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping Mute for Movie
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping VolumeDown for Movie
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping VolumeUp for Movie
.[37m[1/2/2022, 8:56:07 PM] .[39m.[36m[Living Room Media Center].[39m (Living Room Media Center)INFO - Mapping DirectionDown for Movie

Strangely, the order is not exactly the same in Home app. In Home app the order is: Movie, FM Radio, IP Radio, Music, Game.

**Comment by alapitz** [comment]
I wonder if it is because of the custom mappings. I don't have that setup.
I need to head out for some errands but will take a look once I get back.

**Comment by maisun** [comment]
> 

Can't see why but could be, thanks in advance!

**Comment by alapitz** [comment]
Are you seeing something like this? (Note I should have 9 activities listed
in the input list). I've gotten this to reproduce twice although I'm not
totally sure on the cause. It seems related to
tweaking activitiesToPublishAsInputForTVMode and there being a cached state
some place.

[image: IMG_761992A15F56-1.jpeg]

**Comment by alapitz** [comment]
I spent a while trying to reproduce it not working and wasn't able to. I
did find an accidental ".value" which got removed but adding it back didn't
seem to make a difference for me. I've updated the PR with that change so
that might be worth giving a shot. I'm pretty busy during the work week but
if that doesn't work I'll try debugging it more on my end next weekend.

**Comment by maisun** [comment]
I tried to add the same hub in "otherPlatforms" just for test, my config is as below:
"otherPlatforms": [
                {
                    "name": "Living Room Media Center Test",
                    "hubIP": "192.168.1.XX",
                    "TVAccessory": true,
                    "SortInput": 2,
                    "mainActivity": "IP Radio",
                    "activitiesToPublishAsInputForTVMode": [
                        "IP Radio",
                        "FM Radio",
                        "Music",
                        "Movie",
                        "Game"
                    ],
                    "playPauseBehavior": true,
                    "numberOfCommandsSentForVolumeControl": 2,
                    "addAllActivitiesToSkippedIfSameStateActivitiesList": true
                }
            ]
Unfortunately it still gives me the order Movie, FM Radio, IP Radio, Music, Game, which is neither the order in Harmony nor the order in activity list.

**Comment by alapitz** [comment]
I haven't been able to reproduce the issue on my side at all. I've updated
the PR with additional debug logging to see if I can catch what is going on
in your config.

Thanks,
-Adam

**Comment by nicoduj** [comment]
@maisun did you try alpha order (1) and not 2. As I said harmony conf order is not the same as the app, did not find any other info but I think the order in the app is custom and made by the app itself :the app can reorder the activities and I think it is saved only locally. Indeed, in my iPhone app and my iPad app the order is not the same, so it is not synced back to the hub. The order on the hub must be the one at creation time I think.

**Comment by maisun** [comment]
> I haven't been able to reproduce the issue on my side at all. I've updated the PR with additional debug logging to see if I can catch what is going on in your config. Thanks, -Adam
> […](#)

Hi Adam, thanks for helping out! Just tried to patch with your new commit in PR and got the following error:
/homebridge/node_modules/homebridge-harmony/harmonySubPlatform.js:259
      this.log('(' + this.name + ')' + 'INFO - Creating Input Service - ' + inputName + ' in position ' + order);
                                                                                                          ^
ReferenceError: order is not defined
    at HarmonySubPlatform.configureInputSourceService (/homebridge/node_modules/homebridge-harmony/harmonySubPlatform.js:259:107)
    at HarmonySubPlatform.readTVAccessories (/homebridge/node_modules/homebridge-harmony/harmonySubPlatform.js:164:39)
    at HarmonySubPlatform.readAccessories (/homebridge/node_modules/homebridge-harmony/harmonySubPlatform.js:91:78)
    at /homebridge/node_modules/homebridge-harmony/harmonyBase.js:107:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Please ignore the line number for some reason the file was formatted when I saved it, also I removed the debug so I can see it in info log.

**Comment by maisun** [comment]
> @maisun did you try alpha order (1) and not 2. As I said harmony conf order is not the same as the app, did not find any other info but I think the order in the app is custom and made by the app itself :the app can reorder the activities and I think it is saved only locally. Indeed, in my iPhone app and my iPad app the order is not the same, so it is not synced back to the hub. The order on the hub must be the one at creation time I think.

Hi, thanks for your reply! I also tried option 1 but got the same result......

**Comment by alapitz** [comment]
That is weird... if you don't have order defined the merge might be where
the issue is. Can you confirm line 453 looks like this "
configureInputSourceService: function (accessory, inputName, inputId,
activity, order) {" ?

**Comment by maisun** [comment]
> That is weird... if you don't have order defined the merge might be where the issue is. Can you confirm line 453 looks like this " configureInputSourceService: function (accessory, inputName, inputId, activity, order) {" ?
> […](#)

Actually mine doesn't have order:   configureInputSourceService: function(accessory, inputName, inputId, activity) - Line 452.
But I double checked the version is 1.5.4. The file I'm checking is harmonySubPlatform.js.

**Comment by maisun** [comment]
@nicoduj: could it be an issue with merge? I can see the latest version doesn't include the change Adam committed in PR..

**Comment by nicoduj** [comment]
I did not merge this pr right now, you have to test manually. I did no do so since I wan o do more tests, and check if the optional char used for the order is the right one

**Comment by maisun** [comment]
> I did not merge this pr right now, you have to test manually. I did no do so since I wan o do more tests, and check if the optional char used for the order is the right one

Ok my bad I should have checked. I just saw in the gui the option SortInput is available, so I assumed the code is already integrated into master.

**Comment by alapitz** [comment]
I think I just realized what is going on, I just realized we are discussing
the first PR. Nicolas, can you double check you've got both "Sort Updates"
and "Sort the activities alphabetically" applied. The combination of the
ids not being correctly converted and the incorrect key caused the first PR
to not work. The second PR fixes that, if you are still having issues can
you run with debug mode enabled and share the logs.

**Comment by maisun** [comment]
Hi @nicoduj, @alapitz:
I have now patched with @alapitz's PR and below are my observations:
1) SortInput=1 works well without the need to remove/re-add the accessory, however I assume it's not most needed
2) SortInput=2 still doesn't work for me. Maybe Harmony has some internal order which is not reflected by the order displayed in Harmony app. Anyways for me the sorting is the same as the default order
3) What would be really nice and maybe easier to implement is to honour the order defined by user in  "activitiesToPublishAsInputForTVMode". So in this case user can define both the activities to be included and their order.

**Comment by maisun** [comment]
Ok. I did some further test and now for some reason I cannot control harmony anymore, I receive the following error when I try to operate Harmony via HomeKit:
[1/4/2022, 6:10:09 PM] [homebridge-harmony] This plugin threw an error from the characteristic 'Active': Unhandled error thrown inside write handler for characteristic: Cannot read properties of undefined (reading 'activityName'). See https://git.io/JtMGR for more info.
I hav rolledback t o version 1.5.4 the problem persists, any hint on how to fix it?

**Pull request merged**
